1.)

DECLARE
P NUMBER:=400;
T NUMBER:=3;
R NUMBER:=8;
SI NUMBER;

BEGIN 
SI:=(P*T*R)/100;
DBMS_OUTPUT.PUT_LINE("SI = "||SI);
END;

2.)

DECLARE
EMP_NAME VARCHAR2(50):='ASHRITHA';
SALARY NUMBER:=50000;
BONUS NUMBER;
BEGIN
IF SALARY>50000 THEN
BONUS:=0.10*SALARY;
DBMS_OUTPUT.PUT_LINE(EMP_NAME||' '||SALARY||' '|| BONUS);
ELSE
BONUS:=0.15*SALARY;
DBMS_OUTPUT.PUT_LINE(EMP_NAME||' '|| SALARY|| ' ' || BONUS);
END IF;
END;

3.)

DECLARE 
V_DEPT DEPARTMENTS%ROWTYPE;
BEGIN
SELECT * INTO V_DEPT FROM DEPARTMENTS WHERE DEPT_NO=101;
DBMS_OUTPUT.PUT_LINE('DEPARTMENT NAME: '||V_DEPT.DNAME||'LOCATION : '||V_DEPT.LOC);
END;

4.)

DECLARE
TYPE MARKS_TABLE IS TABLE OF NUMBER INDEX BY VARCHAR2(30);
STUDENT_MARKS MARKS_TABLE;

TOTAL_MARKS NUMBER:=0;
AVG_MARKS NUMBER :=0;
STUDENT_NAME VARCHAR(20);
COUNTER NUMBER:=0;
BEGIN
STUDENT_MARKS('KRISHNA'):=95;
STUDENT_MARKS('RAMESH'):=80;
STUDENT_MARKS('VINU'):=75;
STUDENT_MARKS('ANU'):=50;
STUDENT_MARKS('ROSE'):=85;

DBMS_OUTPUT.PUT_LINE('STUDENT MARKS LIST:');
STUDENT_NAME :=STUDENT_MARKS.FIRST;
WHILE STUDENT_NAME IS NOT NULL LOOP
DBMS_OUTPUT.PUT_LINE(STUDENT_NAME||':'||STUDENT_MARKS(STUDENT_NAME));
TOTAL_MARKS:=TOTAL_MARKS+STUDENT_MARKS(STUDENT_NAME);
COUNTER:=COUNTER+1;
STUDENT_NAME:=STUDENT_MARKS.NEXT(STUDENT_NAME);
END LOOP;
AVG_MARKS:=TOTAL_MARKS/COUNTER;
DBMS_OUTPUT.PUT_LINE('TOTAL MARKS: '||TOTAL_MARKS);
DBMS_OUTPUT.PUT_LINE('AVG MARKS : '||ROUND(AVG_MARKS,2));
END;

5.)

DECLARE
TYPE country_capital_table IS TABLE OF VARCHAR2(50) INDEX BY VARCHAR2(50);
country_capital country_capital_table;
v_country VARCHAR2(50);
BEGIN
country_capital('INDIA'):='NEW DELHI';
country_capital('USA'):='WASHINGTON';
country_capital('FRANCE'):='PARIS';
country_capital('AUSTRALIA'):='CANBERRA';
country_capital('GERMANY'):='BERLIN';

v_country:='&enter_country_name';
IF country_capital.EXISTS(v_country) THEN
DBMS_OUTPUT.PUT_LINE('THE CAPITAL OF'||v_country||' is '||country_capital(v_country));
ELSE
DBMS_OUTPUT.PUT_LINE('COUNTRY NOT IN LIST');
END IF;
END;
